development:
  adapter: postgresql
  encoding: unicode
  database: dolphin_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: dolphin_test
  pool: 5
  host: localhost

cucumber:
  <<: *test
